name: 🐞 Bug Report
description: 报告一个可复现的问题
title: "[Bug]: "
labels: ["bug"]

body:
  - type: dropdown  
    id: Component
    attributes:
      label: 问题模块
      options:
        - 注册/登录
        - 首页
        - 概览 Overview
        - Thino 管理/ Thino
        - 图库/ Gallery
        - 白板/ canvas
        - 复习/ review
        - 文章/ writing
        - 模板/ template
        - AI
        - 设置
        - 日历
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      description: 请清楚描述问题（建议按「1. 2. 3.」步骤编写，方便复现）
      placeholder: | 
        发生了什么？
        1. 打开XX功能/页面
        2. 执行XX操作（如点击按钮、输入内容）
        3. 出现XX异常现象
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: 设备
      options:
        - Windows
        - Mac
        - Linux
        - iOS
        - Android
    validations:
      required: true

  - type: dropdown  
    id: browser
    attributes:
      label: 浏览器
      options:
        - Edge
        - Chrome
        - Safari
        - other
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: 期望行为/实际行为
      placeholder: 请描述你期望/实际发生的结果（如：点击按钮后显示成功提示）
        1. 实际发生了什么
        2. 期望发生什么
    validations:
      required: true

  - type: markdown
    id: images
    attributes:
      value: |
        ### 截图/录屏
        如果适用，请添加截图或录屏以帮助解释您的问题（拖拽文件到输入框即可上传）

  - type: textarea
    id: other_info
    attributes:
      label: 其他信息
      description: 请提供任何其他有助于解决问题的信息（例如：操作系统版本、Thino 版本、网络环境等）
    # 可选：如果需要该字段必填，取消下面注释
    # validations:
    #   required: true
